---
title: "FIFA Player Value Prediction"
author: "Shariq Ahmed Siddiqui"
date: '2022-01-14'
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r include=FALSE}
getwd()

library(tidyverse)
library(readr)
library(dplyr)
library(purrr)
library(magrittr)
library(DataExplorer)
library(maps)
library(DT)
library(gridExtra)
library(stringi)
library(tree)
library(randomForest)
```

```{r}
fifa <- read.csv('FIFA_train.csv')
test <- read.csv("FIFA_test_player_data.csv")
```

```{r}
head(fifa,3)
```

```{r}
#Removing unwanted columns
fifa = subset(fifa, select = -c(player_url,long_name,dob,real_face,
                                nation_position))
test = subset(test, select = -c(player_url,long_name,dob,real_face,
                                nation_position))
```

```{r}
#parsing names correctly
fifa$short_name = parse_character(fifa$short_name, locale = locale(encoding = 'UTF-8'))
fifa$club = parse_character(fifa$club, locale = locale(encoding = 'UTF-8'))

test$short_name = parse_character(test$short_name, locale = locale(encoding = 'UTF-8'))
test$club = parse_character(test$club, locale = locale(encoding = 'UTF-8'))
```

```{r}
#ordering by player rating
fifa = fifa[order(fifa$overall, decreasing = TRUE),]
fifa = fifa[!(is.na(fifa$sofifa_id) == TRUE),]

test = test[order(test$overall, decreasing = TRUE),]
test = test[!(is.na(test$sofifa_id) == TRUE),]
```

```{r}
#Correcting body type
unique(fifa$body_type)
unique(test$body_type)
```

```{r}
#assigning the correct body type to outliers
fifa$body_type = plyr::mapvalues(fifa$body_type, from=c("Messi","C. Ronaldo","Neymar","Courtois","PLAYER_BODY_TYPE_25","Shaqiri","Akinfenwa"), to=c('Normal', 'Normal', 'Lean', 'Normal', 'Normal', 'Stocky', 'Stocky'))

test$body_type = plyr::mapvalues(test$body_type, from=c("Messi","C. Ronaldo","Neymar","Courtois","PLAYER_BODY_TYPE_25","Shaqiri","Akinfenwa"), to=c('Normal', 'Normal', 'Lean', 'Normal', 'Normal', 'Stocky', 'Stocky'))
```

```{r}
unique(fifa$body_type)
unique(test$body_type)
```

```{r}
#Scaling work rate on a numerical scale
unique(fifa$work_rate)
```

```{r}
#mapping values
fifa$work_rate = plyr::mapvalues(fifa$work_rate, from=c("High/High","High/Medium","High/Low","Medium/High","Medium/Medium","Medium/Low","Low/High","Low/Medium","Low/Low"), to=c(9,8,7,6,5,4,3,2,1))

test$work_rate = plyr::mapvalues(test$work_rate, from=c("High/High","High/Medium","High/Low","Medium/High","Medium/Medium","Medium/Low","Low/High","Low/Medium","Low/Low"), to=c(9,8,7,6,5,4,3,2,1))
```

```{r}
unique(fifa$work_rate)
unique(test$work_rate)
```

```{r}
#classifying player positions
unique(fifa$team_position)
#creating position classes
defence <- c("CB", "RB", "LB", "LWB", "RWB", "LCB", "RCB")
midfielder <- c("CM", "CDM","LM","RM", "LCM", "RCM", "LDM", "RDM")
attack <- c("RW", "LW", "ST", "CF", "RAM", "CAM", "LAM", "RS", "LS", "RF", "LF")  
```

```{r}
#players in data set having no on-field position defined 
head(fifa[fifa$team_position ==  "RES" | fifa$team_position ==  "SUB" | fifa$team_position ==  "", 1:20])
```

```{r}
#specifying positions for substitute or reserve players 
for(i in c(1:nrow(fifa))){
  if(fifa$team_position[i] %in% c("SUB", "RES", "")){
    fifa$team_position[i] = sub("\\,.*", "", fifa$player_positions[i])}}
unique(fifa$team_position)

for(i in c(1:nrow(test))){
  if(test$team_position[i] %in% c("SUB", "RES", "")){
    test$team_position[i] = sub("\\,.*", "", test$player_positions[i])}}
unique(test$team_position)
```

```{r}
#assigning players to their respective classes
fifa %<>% mutate(class = if_else(team_position %in% "GK", "Goal Keeper", 
                                if_else(team_position %in% defence, "Defender",
                                       if_else(team_position %in% midfielder, "Midfielder",
                                               if_else(team_position %in% attack, "Forward","NA"))))) 

test %<>% mutate(class = if_else(team_position %in% "GK", "Goal Keeper", 
                                if_else(team_position %in% defence, "Defender",
                                       if_else(team_position %in% midfielder, "Midfielder",
                                               if_else(team_position %in% attack, "Forward","NA")))))          
```

```{r}
head(fifa$class)
head(test$class)
```

```{r}
fifa = replace(fifa,fifa == 'NA',NA)
fifa = replace(fifa,fifa == '',NA)

test = replace(test,test == 'NA',NA)
test = replace(test,test == '',NA)
```

```{r}
#variables ls to rb rate a player's performance in that position
#ratings have been entered as improvement in rating over previous year
head(subset(fifa, select = ls:rb))
typeof(fifa$ls)
```

```{r}
#function that evaluates numerical expressions disguised as characters
#converts a rating from a character "92+2" to numeric 94
converter <- function(x) {
  return (eval(parse(text = x)))}
```

```{r include=FALSE}
#evaluating the ratings, and converting them
new <- apply(subset(fifa, select = attacking_crossing:rb),c(1,2),function(x) converter(x))
newtest <- apply(subset(test, select = attacking_crossing:rb),c(1,2),function(x) converter(x))
```

```{r}
colnames(new)
colnames(newtest)
```

```{r}
#rejoining the transformed numeric ratings
fifa1 = cbind(fifa[,c(1:38,99)], new[,1:60])
test1 = cbind(test[,c(1:37,98)], newtest[,1:60])
```

```{r}
head(fifa1,3)
```

```{r}
summary(fifa1)

#incorrect data entry has led to some negative & >100 ratings 
#keeping values between 0 & 100 for training data:
df1 <- fifa1[between(fifa1$attacking_crossing,0,100) &  between(fifa1$attacking_finishing,0,100) &  between(fifa1$attacking_heading_accuracy,0,100) &  between(fifa1$attacking_short_passing,0,100) &  between(fifa1$attacking_volleys,0,100) &  between(fifa1$skill_dribbling,0,100) &  between(fifa1$skill_curve,0,100) & between(fifa1$skill_fk_accuracy,0,100) & between(fifa1$skill_long_passing,0,100) & between(fifa1$skill_ball_control,0,100) & between(fifa1$movement_acceleration,0,100) & between(fifa1$movement_sprint_speed,0,100) & between(fifa1$movement_agility,0,100) & between(fifa1$movement_reactions,0,100) & between(fifa1$movement_balance ,0,100) & between(fifa1$power_shot_power,0,100) & between(fifa1$power_jumping,0,100) & between(fifa1$power_stamina,0,100) & between(fifa1$power_strength,0,100) & between(fifa1$power_long_shots,0,100) & between(fifa1$mentality_aggression,0,100) & between(fifa1$mentality_interceptions,0,100) & between(fifa1$mentality_positioning,0,100) & between(fifa1$mentality_vision,0,100) & between(fifa1$mentality_penalties,0,100) & between(fifa1$mentality_composure,0,100) & between(fifa1$defending_marking,0,100) & between(fifa1$defending_standing_tackle,0,100) & between(fifa1$defending_sliding_tackle,0,100) & between(fifa1$goalkeeping_diving,0,100) & between(fifa1$goalkeeping_handling,0,100) & between(fifa1$goalkeeping_kicking,0,100) & between(fifa1$goalkeeping_positioning,0,100) & between(fifa1$goalkeeping_reflexes,0,100),]
```

```{r}
#keeping values between 0 & 100 for test:
df1test <- test1[between(test1$attacking_crossing,0,100) &  between(test1$attacking_finishing,0,100) &  between(test1$attacking_heading_accuracy,0,100) &  between(test1$attacking_short_passing,0,100) &  between(test1$attacking_volleys,0,100) &  between(test1$skill_dribbling,0,100) &  between(test1$skill_curve,0,100) & between(test1$skill_fk_accuracy,0,100) & between(test1$skill_long_passing,0,100) & between(test1$skill_ball_control,0,100) & between(test1$movement_acceleration,0,100) & between(test1$movement_sprint_speed,0,100) & between(test1$movement_agility,0,100) & between(test1$movement_reactions,0,100) & between(test1$movement_balance ,0,100) & between(test1$power_shot_power,0,100) & between(test1$power_jumping,0,100) & between(test1$power_stamina,0,100) & between(test1$power_strength,0,100) & between(test1$power_long_shots,0,100) & between(test1$mentality_aggression,0,100) & between(test1$mentality_interceptions,0,100) & between(test1$mentality_positioning,0,100) & between(test1$mentality_vision,0,100) & between(test1$mentality_penalties,0,100) & between(test1$mentality_composure,0,100) & between(test1$defending_marking,0,100) & between(test1$defending_standing_tackle,0,100) & between(test1$defending_sliding_tackle,0,100) & between(test1$goalkeeping_diving,0,100) & between(test1$goalkeeping_handling,0,100) & between(test1$goalkeeping_kicking,0,100) & between(test1$goalkeeping_positioning,0,100) & between(test1$goalkeeping_reflexes,0,100),]
```

```{r}
summary(df1)
```

```{r}
#factorising columns -> 2,7,8,13,18,21,22,26,40
str(df1)
for(i in c(1,6,7,12,17,20,21,24,25,39)) {
  df1[,i] = as.factor(df1[,i])
}
for(i in c(1,6,7,11,16,19,20,23,24,38)) {
  df1test[,i] = as.factor(df1test[,i])
}
```

```{r}
#GKs have values for only GK related variables, therefore separate models will be needed
head(df1[df1$class== 'Goal Keeper',],3)
head(df1test[df1test$class== 'Goal Keeper',],3)

```

```{r}
#train-test split for gk and non gk
set.seed(100)

nongkdf1 <- df1[df1$class != 'Goal Keeper', ]
gkdf1 <- df1[df1$class == 'Goal Keeper', ]

nongktest <- df1test[df1test$class != 'Goal Keeper', ]
gktest <- df1test[df1test$class == 'Goal Keeper', ]

#split of 70-30 for both non gk and gk data frames 
trainnongk <- sample(1: nrow(nongkdf1), nrow(nongkdf1) /1.4)
traingk <- sample(1: nrow(gkdf1), nrow(gkdf1) /1.4)
```

```{r}
nrow(nongkdf1)
nrow(gkdf1)
nrow(nongktest)
nrow(gktest)
length(trainnongk)
```

```{r}
#evaluating release clause NAs
nrow(nongkdf1[is.na(nongkdf1$release_clause_eur),])
hist(nongkdf1[is.na(nongkdf1$release_clause_eur), 'value'])
summary(nongkdf1[is.na(nongkdf1$release_clause_eur), 'value'])
nongkdf1[is.na(nongkdf1$release_clause_eur),]$release_clause_eur <- nongkdf1[is.na(nongkdf1$release_clause_eur),]$value
```

```{r}
summary(gkdf1[is.na(gkdf1$release_clause_eur), 'value'])
gkdf1[is.na(gkdf1$release_clause_eur),]$release_clause_eur <- gkdf1[is.na(gkdf1$release_clause_eur),]$value
```

```{r}
nrow(nongktest[is.na(nongktest$release_clause_eur),])
hist(nongktest$release_clause_eur)
summary(nongktest$release_clause_eur)
nongktest[is.na(nongktest$release_clause_eur),]$release_clause_eur <- exp(1.71 + 0.188*(nongktest[is.na(nongktest$release_clause_eur),]$overall))
```

```{r}
nrow(gktest[is.na(gktest$release_clause_eur),])
gktest[is.na(gktest$release_clause_eur),]$release_clause_eur <- exp(2.341 + 0.1739*(gktest[is.na(gktest$release_clause_eur),]$overall))
```

```{r}
#model building
```

```{r}
#NonGK model
lmnongk.fit <- lm(value~age+height_cm+weight_kg+overall+potential+international_reputation+skill_moves+class+release_clause_eur+pace+shooting+passing+dribbling+defending+physic, data = nongkdf1, subset = trainnongk)

summary(lmnongk.fit)
```

```{r}
#GK model
lmgk.fit <- lm(value~age+height_cm+weight_kg+overall+potential+international_reputation+body_type+release_clause_eur+gk_diving+gk_handling+gk_kicking+gk_reflexes+gk_speed+gk_positioning, data = gkdf1, subset = traingk)

summary(lmgk.fit)
```

```{r}
#NonGK model validation prediction
yhatlmnongk <- predict(lmnongk.fit , newdata = nongkdf1[-trainnongk,])
nongkdf1.testlm <- nongkdf1[-trainnongk,'value']

plot(yhatlmnongk , nongkdf1.testlm)
abline (0, 1)
nongkrmselm <- (mean((yhatlmnongk - nongkdf1.testlm)^2, na.rm = TRUE))^0.5
nongkrsslm <- sum((yhatlmnongk - nongkdf1.testlm)^2, na.rm= TRUE)
nongktsslm <- sum((nongkdf1.testlm - mean(nongkdf1.testlm))^2,  na.rm= TRUE)

#model r-squared and root mean squared error
nongkr2lm <- 1-(nongkrsslm/nongktsslm)
nongkr2lm
nongkrmselm
```

```{r}
#GK model validation prediction
yhatlmgk <- predict(lmgk.fit , newdata = gkdf1[-traingk,])
gkdf1.testlm <- gkdf1[-traingk,'value']

plot(yhatlmgk , gkdf1.testlm)
abline (0, 1)
gkrmselm <- (mean((yhatlmgk - gkdf1.testlm)^2, na.rm = TRUE))^0.5
gkrsslm <- sum((yhatlmgk - gkdf1.testlm)^2, na.rm= TRUE)
gktsslm <- sum((gkdf1.testlm - mean(gkdf1.testlm))^2,  na.rm= TRUE)


#model r-squared and root mean squared error
gkr2lm <- 1-(gkrsslm/gktsslm)
gkr2lm
gkrmselm
```

```{r}
#prediction on test data

#nongk
nongkyhat <- predict(lmnongk.fit , newdata = nongktest)
hist(nongkyhat)
length(nongkyhat)
nrow(nongktest)

nongktest$yhat <- nongkyhat
head(nongktest[, c(1:3, 17,99)])

#gk
gkyhat <- predict(lmgk.fit , newdata = gktest)
hist(gkyhat)
length(gkyhat)
nrow(gktest)

gktest$yhat <- gkyhat
head(gktest[, c(1:3, 17,99)])
```

```{r}
#function that picks the latest entry for players with more than one entry
latest_entry <- function(df, id){
  latest <- max(df[df$sofifa_id == id,'age'])
  target <- df[df$sofifa_id == id & df$age == latest,]
  return(target)
}
```

```{r}
#submission dataset
submission <- read.delim('FIFA_test.csv')
submission <- data.frame(submission)
```

```{r}
#objective: finding the most valuable player from each list of 11 player IDs 
submission[1:3,]
#1462 lists with 11 IDs in each
nrow(submission)
```

```{r}
#converting string of list to list of numeric IDs
submission %<>% mutate(lists = strsplit(submission[,1], ", "))
```

```{r}
head(submission[,2])
```

```{r include=FALSE}
#correcting the first and last elements
for(i in c(1:nrow(submission))){
  x <- submission[[2]][[i]]
  submission[[2]][[i]] <- replace(x, c(1, length(x)), c(substr(x[1], 2, nchar(x[1])),substr(x[length(x)], 1, nchar(x[length(x)])-1)))
}
```

```{r}
head(submission[,2])
```

```{r}
#function which finds the most valuable player from a list of player IDs
maxima <- function(l1){
  x = list()
  #creates a list of IDs as integer-type instead of character
  for (j in c(1:11)){
    x = append(x, as.integer(l1[[1]][[j]]))
  }
  y = list()
  #creates a list of player value predictions for the IDs
  for (i in c(1:11)) {
    #prediction from latest entry is taken from non-gk or gk dataframes  
    if (x[[i]] %in% unique(nongktest$sofifa_id)) {
      target<-latest_entry(nongktest, x[[i]])}
    else {target<-latest_entry(gktest, x[[i]])}
    y = append(y, target$yhat)
  }
  #returns the ID which has the maximum predicted value
  y <- data.frame(y)
  return(x[[match(max(y), table = y)]])
}
```

```{r include=FALSE}
#finding the most valuable player for each list 
submission$most_valued_player_id <- 0
submission$most_valued_player_id <- apply(subset(submission, select = lists), 1 , maxima)
```

```{r}
submission[1:3,]
```

```{r include=FALSE}
#transforming to correct submission format
submission <- submission[,-2]
```

```{r}
#final look at the predicted most valuable player 
submission[1:3,]

write.csv(submission, 'submission.csv' , row.names = FALSE)
```

```{r}
#Thank You
```
